### ISSUE TITLE
To-do: Site Wide Features and Optimisations

### ISSUE THREAD

**Issue by LewisN3142** [LewisN3142/LewisN3142.github.io#3]
- [x] Locally host jquery
- [ ] Get personalised domain name
- [x] Lazy loading for images (Intersection Observer)
- [x] Convert images to Webp to reduce sizes
- [x] Terms and conditions window in place of "all rights reserved"
- [ ] Refactor CSS (add numbers, colours etc to variables and remove redundant code)
- [ ] Language toggle for German/French (see KP theme selector)
- [x] Add sitemap and index with google
- [x] Add closing button to terms and conditions modal and roll out on all pages
