### ISSUE TITLE
To-do: Home Page

### ISSUE THREAD

**Issue by LewisN3142** [LewisN3142/LewisN3142.github.io#4]
Homepage
- [ ] Add hero banner (responsive)
- [x] Add carousel cards for news and updates to home
- [x] Update carousel with clickable dots, touch swipe, slide numbers to aid navigation
- [x] Make roles and activities section more attractive
