### ISSUE TITLE
To-do: Academia Page

### ISSUE THREAD

**Issue by LewisN3142** [LewisN3142/LewisN3142.github.io#5]
Academia page
- [x] Add upcoming presentations
- [ ] Add masters' thesis document
- [ ] Add link to code page (to appear)
