### ISSUE TITLE
To-do: Code Page

### ISSUE THREAD

**Issue by LewisN3142** [LewisN3142/LewisN3142.github.io#8]
Code Page
- [ ] Compile documentation/review into LaTeX PDFs 
- [ ] Add previous code (MATLAB, R, Mathematica, Python, etc) to Github and link to page
- [ ] Format text blocks and dropdowns (brief project descriptions, link to code and documentation as for papers)
